#!/bin/bash

if ! command -v cz >/dev/null && [ "$DEVPOD" = "true" ]; then
  git config --global push.autoSetupRemote true
  git config --global --add safe.directory /workspaces/devops-project/
  uv tool install commitizen
  pre-commit install
  pre-commit install --hook-type commit-msg
fi
